version: '3'

services:
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    networks:
      ukbol_net:
        ipv4_address: 10.0.15.20
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      RUN_MIGRATE: "FALSE"
      FLASK_APP: "ukbol/app:create_app"
      FLASK_DEBUG: "true"
      UKBOL_SQLALCHEMY_DATABASE_URI: postgresql+psycopg://admin:password@db/ukbol
    volumes:
      - ./api:/app/api

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ukbol
    networks:
      - ukbol_net
    volumes:
      - db_data:/var/lib/postgresql/data/

networks:
  ukbol_net:
    ipam:
      config:
        - subnet: "10.0.15.0/24"

volumes:
  db_data:
