version: "3"

services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    command: "-c max_wal_size=2GB"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      # create a database for the app (a test one is created in an init script)
      POSTGRES_DB: ukbol
    networks:
      ukbol_net:
        ipv4_address: 10.0.15.20
    volumes:
      - db_data:/var/lib/postgresql/data/

networks:
  ukbol_net:
    ipam:
      config:
        - subnet: "10.0.15.0/24"

volumes:
  db_data:
