"""
init database.

Revision ID: 507c9999ba67
Revises:
Create Date: 2025-02-11 12:28:00.778280
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507c9999ba67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'specimen',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('specimen_id', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('rank', sa.String(), nullable=True),
        sa.Column('bin_uri', sa.String(), nullable=True),
        sa.Column('country', sa.String(), nullable=True),
        sa.Column('kingdom', sa.String(), nullable=True),
        sa.Column('phylum', sa.String(), nullable=True),
        sa.Column('cls', sa.String(), nullable=True),
        sa.Column('order', sa.String(), nullable=True),
        sa.Column('family', sa.String(), nullable=True),
        sa.Column('subfamily', sa.String(), nullable=True),
        sa.Column('genus', sa.String(), nullable=True),
        sa.Column('species', sa.String(), nullable=True),
        sa.Column('subspecies', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('specimen', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_specimen_bin_uri'), ['bin_uri'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_specimen_country'), ['country'], unique=False
        )

    op.create_table(
        'taxon',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('authorship', sa.String(), nullable=True),
        sa.Column('rank', sa.String(), nullable=False),
        sa.Column('parent_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['parent_id'],
            ['taxon.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('taxon', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_taxon_parent_id'), ['parent_id'], unique=False
        )
        batch_op.create_index(batch_op.f('ix_taxon_rank'), ['rank'], unique=False)

    op.create_table(
        'synonym',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('authorship', sa.String(), nullable=True),
        sa.Column('rank', sa.String(), nullable=False),
        sa.Column('taxon_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['taxon_id'],
            ['taxon.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('synonym', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_synonym_taxon_id'), ['taxon_id'], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('synonym', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_synonym_taxon_id'))

    op.drop_table('synonym')
    with op.batch_alter_table('taxon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taxon_rank'))
        batch_op.drop_index(batch_op.f('ix_taxon_parent_id'))

    op.drop_table('taxon')
    with op.batch_alter_table('specimen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specimen_country'))
        batch_op.drop_index(batch_op.f('ix_specimen_bin_uri'))

    op.drop_table('specimen')
    # ### end Alembic commands ###
