"""
add pantheon table.

Revision ID: c6b63b1b8a10
Revises: c22e5eca6a4d
Create Date: 2025-03-07 18:25:54.095263
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b63b1b8a10'
down_revision = 'c22e5eca6a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pantheon_species',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('species', sa.String(), nullable=True),
        sa.Column('family', sa.String(), nullable=True),
        sa.Column('order', sa.String(), nullable=True),
        sa.Column('sqs', sa.String(), nullable=True),
        sa.Column('conservation_status', sa.String(), nullable=True),
        sa.Column('larval_feeding_guild', sa.String(), nullable=True),
        sa.Column('adult_feeding_guild', sa.String(), nullable=True),
        sa.Column('broad_biotope', sa.String(), nullable=True),
        sa.Column('habitat', sa.String(), nullable=True),
        sa.Column('resources', sa.String(), nullable=True),
        sa.Column('specific_assemblage_type', sa.String(), nullable=True),
        sa.Column('habitat_score', sa.String(), nullable=True),
        sa.Column('associations', sa.String(), nullable=True),
        sa.Column('common_name', sa.String(), nullable=True),
        sa.Column('notes', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('pantheon_species', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_pantheon_species_species'), ['species'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_pantheon_species_specific_assemblage_type'),
            ['specific_assemblage_type'],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pantheon_species', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pantheon_species_specific_assemblage_type'))
        batch_op.drop_index(batch_op.f('ix_pantheon_species_species'))

    op.drop_table('pantheon_species')
    # ### end Alembic commands ###
