"""add data source status table

Revision ID: e4a164b35bc4
Revises: c6b63b1b8a10
Create Date: 2025-03-17 01:08:28.507379

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e4a164b35bc4"
down_revision = "c6b63b1b8a10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_source_status",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_source_status")
    # ### end Alembic commands ###
