name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "api/.python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.1"

      - name: Install dependencies
        run: uv sync

      - name: Activate virtualenv
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Lint code
        run: ruff check api/ukbol api/tests

      - name: Format code
        run: ruff format --check api/ukbol api/tests

      - name: Run database for tests
        run: docker compose up db --wait

      - name: Run tests
        env:
          PYTHONUNBUFFERED: 1
          PYTHONDONTWRITEBYTECODE: 1
          FLASK_APP: "ukbol/app:create_app"
          FLASK_DEBUG: true
          UKBOL_SQLALCHEMY_DATABASE_URI: "postgresql+psycopg://admin:password@10.0.15.20/test"
        run: pytest --cov=ukbol tests

      - name: Run coveralls
        uses: coverallsapp/github-action@v2

      - name: Shutdown database
        if: always()
        run: docker compose down
